searches:
  - id: studio_saint_denis
    name: "Studio — Saint-Denis"
    platform: "leboncoin"
    url: "https://www.leboncoin.fr/recherche?category=10&text=NOT+t2+NOT+f2+NOT+t3+NOT+f3&locations=Saint-Denis__-20.905210884748794_55.475948319967685_7424_5000&price=min-800&furnished=1&owner_type=all&sort=time&order=desc&from=ms&sa=2026-04-27T05%3A32%3A29.251404Z"
    location: "Saint-Denis, La Réunion"
    property_type: "Studio"
    metric: "total_listings_count"
    active: true

  - id: t2_t3_saint_denis
    name: "T2 / T3 — Saint-Denis"
    platform: "leboncoin"
    url: "https://www.leboncoin.fr/recherche?category=10&text=NOT+studio+NOT+t1+NOT+f1&locations=Saint-Denis__-20.905210884748794_55.475948319967685_7424_1000&price=min-1000&furnished=1&real_estate_type=2&owner_type=all&sort=time&order=desc&from=ms&sa=2026-03-28T17%3A04%3A40.693455Z"
    location: "Saint-Denis, La Réunion"
    property_type: "T2/T3"
    metric: "total_listings_count"
    active: true

  - id: t3_saint_denis
    name: "T3 — Saint-Denis"
    platform: "leboncoin"
    url: "https://www.leboncoin.fr/recherche?category=10&text=NOT+studio+NOT+t1+NOT+f1+t3+OR+f3+OR+%223+pi%C3%A8ces%22+OR+%222+chambres%22&locations=Saint-Denis__-20.905210884748794_55.475948319967685_7424_5000&furnished=1&real_estate_type=2&owner_type=all&sort=time&order=desc&from=ms&sa=2026-03-28T17%3A07%3A02.056977Z"
    location: "Saint-Denis, La Réunion"
    property_type: "T3"
    metric: "total_listings_count"
    active: true
